services:
  frontend:
    container_name: frontend
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - frontend-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api-gateway

  engage-hub-service:
    container_name: engage-hub-service
    build:
      context: ./apps/engage-hub-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/engage-hub-service:/app
      - engage-hub-service-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=engage-db
      - DB_USER=engage
      - DB_PASSWORD=engage
      - DB_NAME=engage
      - DB_PORT=3306
    depends_on:
      - engage-db

  training-agenda-service:
    container_name: training-agenda-service
    build:
      context: ./apps/training-agenda-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./apps/training-agenda-service:/app
      - training-agenda-service-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - training-db

  ai-service:
    container_name: ai-service
    build:
      context: ./apps/ai-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./apps/ai-service:/app
      - ai-service-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  payment-service:
    container_name: payment-service
    build:
      context: ./apps/payment-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./apps/payment-service:/app
      - payment-service-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - payment-db

  auth-service:
    container_name: auth-service
    build:
      context: ./apps/auth-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./apps/auth-service:/app
      - auth-service-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - auth-db

  api-gateway:
    container_name: api-gateway
    build:
      context: ./infraestructure/api-gateway
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    volumes:
      - ./infraestructure/api-gateway:/app
      - api-gateway-node_modules:/app/node_modules
    depends_on:
      - engage-hub-service
      - training-agenda-service
      - ai-service
      - payment-service
      - auth-service
    environment:
      - NODE_ENV=development

  engage-db:
    container_name: engage-db
    image: mysql:9.0.1
    ports:
      - "4000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: engage
      MYSQL_DATABASE: engage
      MYSQL_USER: engage
      MYSQL_PASSWORD: engage
    volumes:
      - mysql-engage:/var/lib/mysql

  training-db:
    container_name: training-db
    image: mongo
    ports:
      - "4001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: training
      MONGO_INITDB_ROOT_PASSWORD: training
      MONGO_INITDB_DATABASE: training
    volumes:
      - mongo-training:/data/db

  payment-db:
    container_name: payment-db
    image: mysql:9.0.1
    ports:
      - "4002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: payment
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment
    volumes:
      - mysql-payment:/var/lib/mysql

  auth-db:
    container_name: auth-db
    image: mongo
    ports:
      - "4003:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: auth
      MONGO_INITDB_ROOT_PASSWORD: auth
      MONGO_INITDB_DATABASE: auth
    volumes:
      - mongo-auth:/data/db
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    command: start-dev

  keycloak-db:
    image: mysql:8.0
    container_name: keycloak-db
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3308:3306"
    volumes:
      - mysql-keycloak:/var/lib/mysql

volumes:
  frontend-node_modules:
  engage-hub-service-node_modules:
  training-agenda-service-node_modules:
  ai-service-node_modules:
  payment-service-node_modules:
  auth-service-node_modules:
  api-gateway-node_modules:
  mysql-engage:
  mongo-training:
  mysql-payment:
  mongo-auth:
  mysql-keycloak:
